apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 0  # Ensures no downtime
  #     maxSurge: 1  # Creates a new pod before deleting the old one
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret  # ✅ Uses Kubernetes secret for GHCR authentication
      containers:
        - name: auth-service
          image: ghcr.io/mickeymcgoo/auth-service/auth-service:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health  # ✅ Check if the app is ready before sending traffic
          #     port: 9090
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health  # ✅ Restart pod if this check fails
          #     port: 9090
          #   initialDelaySeconds: 10
          #   periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090  # Exposes the service on localhost:30090
