name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main  # ✅ Ensures CD runs only when CI on 'main' completes

jobs:
  deploy:
    name: Deploy to Minikube
    runs-on: self-hosted  # ✅ Uses your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Ensure Minikube is Running
        run: |
          if ! minikube status | grep -q "Running"; then
            echo "Starting Minikube..."
            minikube start --cpus 4 --memory 8192
          else
            echo "Minikube is already running."
          fi

      - name: Set Minikube Docker Daemon
        run: eval $(minikube docker-env)

      - name: Pull Latest Image from GHCR
        run: docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/my-auth-service:latest

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f k8s-deployment.yml

      - name: Wait for Deployment to Complete
        run: kubectl rollout status deployment/auth-service

      - name: Get Service URL
        run: minikube service auth-service --url
